# Generated by Django 4.2.23 on 2025-07-23 01:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PollutionData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(verbose_name="日期时间")),
                ("pm25", models.FloatField(verbose_name="PM2.5浓度(μg/m³)")),
                ("pm10", models.FloatField(verbose_name="PM10浓度(μg/m³)")),
                ("temperature", models.FloatField(verbose_name="温度(℃)")),
                ("humidity", models.FloatField(verbose_name="湿度(%)")),
                ("wind_speed", models.FloatField(verbose_name="风速(m/s)")),
            ],
            options={
                "verbose_name": "历史污染数据",
                "verbose_name_plural": "历史污染数据",
            },
        ),
        migrations.CreateModel(
            name="PredictionResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "predict_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="预测时间"
                    ),
                ),
                ("target_date", models.DateTimeField(verbose_name="预测目标日期")),
                ("pm25_pred", models.FloatField(verbose_name="PM2.5预测值")),
                ("pm10_pred", models.FloatField(verbose_name="PM10预测值")),
                (
                    "accuracy",
                    models.FloatField(blank=True, null=True, verbose_name="预测准确率(%)"),
                ),
            ],
            options={
                "verbose_name": "预测结果",
                "verbose_name_plural": "预测结果",
            },
        ),
    ]
