# Generated by Django 4.2.23 on 2025-07-23 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("pollution_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="uploads/")),
                ("upload_date", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(default="处理中", max_length=20)),
                ("records_processed", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "pollution_data",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="pollution_app.pollutiondata",
                        verbose_name="关联的污染数据",
                    ),
                ),
            ],
            options={
                "verbose_name": "数据上传记录",
                "verbose_name_plural": "数据上传记录",
            },
        ),
    ]
