# Generated by Django 4.2.23 on 2025-08-05 15:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pollution_app", "0002_dataupload"),
    ]

    operations = [
        migrations.AddField(
            model_name="pollutiondata",
            name="co",
            field=models.FloatField(default=0, verbose_name="CO浓度(mg/m³)"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pollutiondata",
            name="no2",
            field=models.FloatField(default=0, verbose_name="NO₂浓度(μg/m³)"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pollutiondata",
            name="o3",
            field=models.FloatField(default=0, verbose_name="O₃浓度(μg/m³)"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pollutiondata",
            name="so2",
            field=models.FloatField(default=0, verbose_name="SO₂浓度(μg/m³)"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="predictionresult",
            name="co_pred",
            field=models.FloatField(default=0, verbose_name="CO预测值"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="predictionresult",
            name="no2_pred",
            field=models.FloatField(default=0, verbose_name="NO₂预测值"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="predictionresult",
            name="o3_pred",
            field=models.FloatField(default=0, verbose_name="O₃预测值"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="predictionresult",
            name="so2_pred",
            field=models.FloatField(default=0, verbose_name="SO₂预测值"),
            preserve_default=False,
        ),
    ]
