# Generated by Django 4.2.23 on 2025-10-19 18:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pollution_app", "0004_searchhistory_userpollutant"),
    ]

    operations = [
        migrations.AddField(
            model_name="predictionresult",
            name="aqi_level_pred",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="AQI等级预测"
            ),
        ),
        migrations.AddField(
            model_name="predictionresult",
            name="main_pollutant_pred",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="主要污染物预测"
            ),
        ),
        migrations.AddField(
            model_name="predictionresult",
            name="overall_aqi_pred",
            field=models.IntegerField(blank=True, null=True, verbose_name="综合AQI预测值"),
        ),
    ]
