# Generated by Django 4.2.23 on 2025-10-20 12:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pollution_app", "0005_predictionresult_aqi_level_pred_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="predictionresult",
            name="co_nn_pred",
            field=models.FloatField(default=0.0, verbose_name="CO预测值（神经网络）"),
        ),
        migrations.AddField(
            model_name="predictionresult",
            name="linear_rmse",
            field=models.JSONField(blank=True, null=True, verbose_name="线性模型RMSE"),
        ),
        migrations.AddField(
            model_name="predictionresult",
            name="nn_rmse",
            field=models.JSONField(blank=True, null=True, verbose_name="神经网络模型RMSE"),
        ),
        migrations.AddField(
            model_name="predictionresult",
            name="no2_nn_pred",
            field=models.FloatField(default=0.0, verbose_name="NO₂预测值（神经网络）"),
        ),
        migrations.AddField(
            model_name="predictionresult",
            name="o3_nn_pred",
            field=models.FloatField(default=0.0, verbose_name="O₃预测值（神经网络）"),
        ),
        migrations.AddField(
            model_name="predictionresult",
            name="pm10_nn_pred",
            field=models.FloatField(default=0.0, verbose_name="PM10预测值（神经网络）"),
        ),
        migrations.AddField(
            model_name="predictionresult",
            name="pm25_nn_pred",
            field=models.FloatField(default=0.0, verbose_name="PM2.5预测值（神经网络）"),
        ),
        migrations.AddField(
            model_name="predictionresult",
            name="so2_nn_pred",
            field=models.FloatField(default=0.0, verbose_name="SO₂预测值（神经网络）"),
        ),
        migrations.AlterField(
            model_name="predictionresult",
            name="co_pred",
            field=models.FloatField(verbose_name="CO预测值（线性）"),
        ),
        migrations.AlterField(
            model_name="predictionresult",
            name="no2_pred",
            field=models.FloatField(verbose_name="NO₂预测值（线性）"),
        ),
        migrations.AlterField(
            model_name="predictionresult",
            name="o3_pred",
            field=models.FloatField(verbose_name="O₃预测值（线性）"),
        ),
        migrations.AlterField(
            model_name="predictionresult",
            name="pm10_pred",
            field=models.FloatField(verbose_name="PM10预测值（线性）"),
        ),
        migrations.AlterField(
            model_name="predictionresult",
            name="pm25_pred",
            field=models.FloatField(verbose_name="PM2.5预测值（线性）"),
        ),
        migrations.AlterField(
            model_name="predictionresult",
            name="so2_pred",
            field=models.FloatField(verbose_name="SO₂预测值（线性）"),
        ),
    ]
