# Generated by Django 4.2.23 on 2025-10-20 13:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pollution_app", "0006_predictionresult_co_nn_pred_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="predictionresult",
            name="accuracy",
        ),
        migrations.AddField(
            model_name="predictionresult",
            name="linear_accuracy",
            field=models.FloatField(blank=True, null=True, verbose_name="线性回归准确率(%)"),
        ),
        migrations.AddField(
            model_name="predictionresult",
            name="nn_accuracy",
            field=models.FloatField(blank=True, null=True, verbose_name="神经网络准确率(%)"),
        ),
    ]
