# Generated by Django 4.2.23 on 2025-10-20 17:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pollution_app", "0007_remove_predictionresult_accuracy_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pollutiondata",
            name="precipitation",
            field=models.FloatField(default=0.0, verbose_name="降水量"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pollutiondata",
            name="pressure",
            field=models.FloatField(default=0.0, verbose_name="气压"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pollutiondata",
            name="wind_direction",
            field=models.FloatField(default=0.0, verbose_name="风向"),
            preserve_default=False,
        ),
    ]
