# Generated by Django 4.2.23 on 2025-10-20 17:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "pollution_app",
            "0008_pollutiondata_precipitation_pollutiondata_pressure_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="pollutiondata",
            name="is_hidden",
            field=models.BooleanField(default=False, verbose_name="是否隐藏"),
        ),
    ]
