# Generated by Django 4.2.23 on 2025-10-29 15:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pollution_app", "0009_pollutiondata_is_hidden"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelEvaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.CharField(max_length=50, verbose_name="模型名称")),
                ("city", models.CharField(max_length=50, verbose_name="城市")),
                ("pollutant", models.CharField(max_length=20, verbose_name="污染物")),
                ("train_mae", models.FloatField(verbose_name="训练集MAE")),
                ("train_rmse", models.FloatField(verbose_name="训练集RMSE")),
                ("train_r2", models.FloatField(verbose_name="训练集R²")),
                ("test_mae", models.FloatField(verbose_name="测试集MAE")),
                ("test_rmse", models.FloatField(verbose_name="测试集RMSE")),
                ("test_r2", models.FloatField(verbose_name="测试集R²")),
                ("training_time", models.FloatField(verbose_name="训练时间(秒)")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="记录时间"),
                ),
            ],
            options={
                "verbose_name": "模型评估指标",
                "verbose_name_plural": "模型评估指标",
            },
        ),
    ]
