# Generated by Django 6.0.2 on 2026-02-16 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollution_app', '0010_modelevaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionresult',
            name='co_rf_pred',
            field=models.FloatField(default=0.0, verbose_name='CO预测值（随机森林）'),
        ),
        migrations.AddField(
            model_name='predictionresult',
            name='no2_rf_pred',
            field=models.FloatField(default=0.0, verbose_name='NO₂预测值（随机森林）'),
        ),
        migrations.AddField(
            model_name='predictionresult',
            name='o3_rf_pred',
            field=models.FloatField(default=0.0, verbose_name='O₃预测值（随机森林）'),
        ),
        migrations.AddField(
            model_name='predictionresult',
            name='pm10_rf_pred',
            field=models.FloatField(default=0.0, verbose_name='PM10预测值（随机森林）'),
        ),
        migrations.AddField(
            model_name='predictionresult',
            name='pm25_rf_pred',
            field=models.FloatField(default=0.0, verbose_name='PM2.5预测值（随机森林）'),
        ),
        migrations.AddField(
            model_name='predictionresult',
            name='rf_accuracy',
            field=models.FloatField(blank=True, null=True, verbose_name='随机森林准确率(%)'),
        ),
        migrations.AddField(
            model_name='predictionresult',
            name='so2_rf_pred',
            field=models.FloatField(default=0.0, verbose_name='SO₂预测值（随机森林）'),
        ),
    ]
