# Generated by Django 6.0.2 on 2026-02-16 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollution_app', '0011_predictionresult_co_rf_pred_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelevaluation',
            name='hyperparameters',
            field=models.JSONField(default=dict, verbose_name='超参数'),
        ),
        migrations.AddField(
            model_name='modelevaluation',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='是否激活'),
        ),
        migrations.AddField(
            model_name='modelevaluation',
            name='model_type',
            field=models.CharField(choices=[('linear', '线性回归'), ('ridge', '岭回归'), ('lasso', 'Lasso回归'), ('rf', '随机森林'), ('gb', '梯度提升'), ('svr', '支持向量回归'), ('mlp', '神经网络')], default='rf', max_length=20, verbose_name='模型类型'),
        ),
        migrations.AddField(
            model_name='modelevaluation',
            name='version',
            field=models.CharField(default='v1.0', max_length=20, verbose_name='模型版本'),
        ),
        migrations.AlterUniqueTogether(
            name='modelevaluation',
            unique_together={('model_name', 'version', 'pollutant')},
        ),
    ]
