# Generated by Django 6.0.2 on 2026-02-16 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollution_app', '0013_permission_role_rolepermission_userrole'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_name', models.CharField(max_length=50, verbose_name='版本名称')),
                ('description', models.TextField(blank=True, verbose_name='版本描述')),
                ('data_count', models.IntegerField(default=0, verbose_name='数据条数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_active', models.BooleanField(default=False, verbose_name='是否激活')),
                ('upload_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='上传用户')),
            ],
            options={
                'verbose_name': '数据版本',
                'verbose_name_plural': '数据版本管理',
            },
        ),
        migrations.CreateModel(
            name='PollutionDataVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pollution_app.pollutiondata', verbose_name='污染数据')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pollution_app.dataversion', verbose_name='数据版本')),
            ],
            options={
                'verbose_name': '数据版本关联',
                'verbose_name_plural': '数据版本关联管理',
                'unique_together': {('data', 'version')},
            },
        ),
    ]
