# Generated by Django 6.0.2 on 2026-02-16 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollution_app', '0014_dataversion_pollutiondataversion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_usage', models.FloatField(verbose_name='CPU使用率')),
                ('memory_usage', models.FloatField(verbose_name='内存使用率')),
                ('disk_usage', models.FloatField(verbose_name='磁盘使用率')),
                ('network_in', models.FloatField(verbose_name='网络入流量')),
                ('network_out', models.FloatField(verbose_name='网络出流量')),
                ('active_connections', models.IntegerField(verbose_name='活跃连接数')),
                ('response_time', models.FloatField(verbose_name='响应时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
            ],
            options={
                'verbose_name': '系统状态',
                'verbose_name_plural': '系统状态管理',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('info', '信息'), ('warning', '警告'), ('error', '错误'), ('critical', '严重')], default='info', max_length=10, verbose_name='日志级别')),
                ('action', models.CharField(choices=[('login', '登录'), ('logout', '退出'), ('data_upload', '数据上传'), ('data_export', '数据导出'), ('model_train', '模型训练'), ('model_deploy', '模型部署'), ('version_create', '版本创建'), ('version_activate', '版本激活'), ('system_settings', '系统设置'), ('user_management', '用户管理'), ('role_management', '角色管理'), ('other', '其他')], default='other', max_length=20, verbose_name='操作类型')),
                ('message', models.TextField(verbose_name='日志内容')),
                ('ip_address', models.CharField(blank=True, max_length=50, verbose_name='IP地址')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='用户代理')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作用户')),
            ],
            options={
                'verbose_name': '系统日志',
                'verbose_name_plural': '系统日志管理',
                'ordering': ['-created_at'],
            },
        ),
    ]
