# Generated by Django 6.0.2 on 2026-02-16 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollution_app', '0015_systemstatus_systemlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollutiondata',
            name='city',
            field=models.CharField(default='贺州市', max_length=50, verbose_name='城市'),
        ),
    ]
