# Generated by Django 6.0.2 on 2026-02-16 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollution_app', '0016_pollutiondata_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityPollutionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50, unique=True, verbose_name='城市名称')),
                ('aqi', models.IntegerField(verbose_name='AQI指数')),
                ('pm25', models.FloatField(verbose_name='PM2.5浓度(μg/m³)')),
                ('pm10', models.FloatField(verbose_name='PM10浓度(μg/m³)')),
                ('no2', models.FloatField(verbose_name='NO₂浓度(μg/m³)')),
                ('so2', models.FloatField(verbose_name='SO₂浓度(μg/m³)')),
                ('o3', models.FloatField(verbose_name='O₃浓度(μg/m³)')),
                ('co', models.FloatField(verbose_name='CO浓度(mg/m³)')),
                ('quality', models.CharField(max_length=20, verbose_name='空气质量等级')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '城市污染数据',
                'verbose_name_plural': '城市污染数据',
                'ordering': ['aqi'],
            },
        ),
        migrations.RemoveField(
            model_name='pollutiondata',
            name='city',
        ),
    ]
