# Generated by Django 6.0.2 on 2026-02-24 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollution_app', '0017_citypollutiondata_remove_pollutiondata_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='用户名')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='邮箱')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='是否超级用户')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户管理',
                'ordering': ['-created_at'],
            },
        ),
    ]
